### ISSUE TITLE
Design Booking view

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#100]
Student Booking view -> Click on a list item -> Booking view

Display the tutor's name, rating, rate, and available time slots.

Add a button "Book now". After clicking the book now button, the user should be navigated to the payment view.

**Comment by ConnorWalsh7** [comment]
-Designed booking view to closly match tutor profile view
-Displays a tutors rating, school, rate, location, courses, and availability
-Book now button takes you to the StudentPaymentFragment
-Passing any variables needed to create a new session through bundles into this view
-On a successful payment a new session is created and the user is redirected to the session details
-Added a DateFormatHelper for converting our dates into more readable strings
-Added various helper methods in some of the models for getting the data I needed for the booking view
-Added a seeder for available_times to test the booking view
