### ISSUE TITLE
Fix photo gallery bug

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#102]
Uploading a picture using the photo gallery is currently not working. This needs to be investigated.

**Comment by ConnorWalsh7** [comment]
Just fixed this. Issue was when picking an image from the gallery, it would send back the bitmap image itself, but we only wanted to save the path to that image. Trying to get the path of the image was not working well, it was only giving a relative path, and also had the issue of if the user deleted that image from the gallery, we would be trying to load a non-existent image and likely crash the app. 

Now after getting the bitmap image from the gallery, we make a copy and store it in the same place as the images from the camera activity and they load properly

**Comment by Mons1Oerjan** [comment]
awesome work, Connor! Thanks for fixing this.
