### ISSUE TITLE
Design the Student Upcoming Sessions list item view

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#104]
- display upcoming session information
- Add functionality to cancel the session (red button "cancel session")

**Comment by Mons1Oerjan** [comment]
Feel free to use this PR as a guidance for designing the view: #109

**Comment by Mons1Oerjan** [comment]
@gregpmillr I also added a cancel button and delete functionality in my PR. This will be super useful (almost copy / paste) for your task. Check it out at #109

**Comment by Mons1Oerjan** [comment]
Right now the Student upcoming session list item view is called `SessionDetailsFragment` and is located in `cs.dal.krush/appfragments`. The layout is called `session_details.xml`. 

For consistency's sake, we should rename these files:
- SessionDetailsFragment ---> StudentUpcSessionsDetailsFragment
- StudentSessionsFragment ---> StudentHistoryFragment
- TutorSessionsFragment ---> TutorHistoryFragment
- TutorSessionsDetailsFragment ---> TutorUpcSessionsDetailsFragment

- session_details.xml ---> student_home_upc_session_details.xml

Also, we should move the StudentUpcSessionsDetailsFragment (old name SessionDetailsFragment) from the `appfragment` package to the `studentfragments` package.

@gregpmillr

**Comment by gregpmillr** [comment]
See PR #128

**Comment by Mons1Oerjan** [comment]
This task is done!
