### ISSUE TITLE
Design a color palette for the app

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#11]
Color palettes were mentioned during class. Use the lecture slides (or other tools) to come up with an appropriate color palette for the application.

To complete this task:
- Implement these colors into the application (change the primary app colors in `/res/values/colors.xml` to the colors in the newly created color palette).
- Make sure that the application uses these colors. Run the app and make sure the app colors are set to the new colors.

**Comment by Mons1Oerjan** [comment]
Our app should be based around a green color palette.

**Comment by ericdesj** [comment]
![screen shot 2017-03-04 at 12 34 02 pm](https://cloud.githubusercontent.com/assets/6282512/23580433/46e08294-00d8-11e7-9978-f693c7a4cb7b.png)

![screen shot 2017-03-04 at 12 34 26 pm](https://cloud.githubusercontent.com/assets/6282512/23580435/49545618-00d8-11e7-80e3-5b3864fb16a6.png)

**Comment by Mons1Oerjan** [comment]
Looks awesome! I'm not sure if "share success" is the right way to go about the logo, but it works for now and for this project. Ideally, we'd want a one-liner that truly describes what this app is all about; i.e students krushing exams with the help of top-notch tutors, or tutors building a portfolio and making it easy to connect with students. We can discuss this, but it's not of high priority at all... 😊

**Comment by ericdesj** [comment]
Ok
