### ISSUE TITLE
Tutor View: Setup Home View (empty view with navigation)

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#14]
The tutor home view includes these sections:

- Upcoming sessions
- Total Revenue made through this app
- Total Rating
- Navigation bar at the bottom of this view linking to other views: Home, Calendar/schedule, Edit Profile, and Session History.

Only navigation functionality is required for now.

**Comment by ConnorWalsh7** [comment]
Added both tutor view and student views into this branch. Will PR into master and add navigation in #1
