### ISSUE TITLE
Write Project Update2

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#18]
Project Update2 is due on March 24th.

The second project update is used to check that your project is nearing completion. The project update should be 3 to 5 pages in length (11 point font) and be divided into the following sections:

- **Title Page:** This includes the title of your project and the group members.
- **Abstract:** A brief 100 word summary of your progress and where you are in your timeline, what milestones have been achieved.
- **Progress Report:** An in-depth progress report, which discusses what has been done to date, what milestones are accomplished, what milestones remain, a revision to the timeline if needed, what problems you encountered, and how were they solved or how you are planning to solve them.
- **Layout:** At this point the majority of your layout should be done and should not change too much. If you have screen shots of some of your screens, include them as well.
- **Prognosis:** A discussion of what functionality (you believe) will be completed and what will not. At this point you should discuss what milestones will be jettisoned and which ones will be accomplished. You should also be starting to think about testing and moving to the polishing phase of your development (assuming you are leaving it to the end).

If the Project Contract needs to be updated, a meeting with the instructor must be scheduled when this update is submitted.

**Comment by Mons1Oerjan** [comment]
Section Delegation:
- @ericdesj: Title Page, Abstract, Progress Report
- @gregpmillr: Layout
- @michaelCasey, @ConnorWalsh7, @mons1oerjan: Prognosis

**Comment by ericdesj** [comment]
The title page, abstract and progress report are done.

**Comment by Mons1Oerjan** [comment]
done!
