### ISSUE TITLE
Plan next sprint's tasks and delegate them

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#23]
We should figure out what tasks we want to accomplish next sprint, create issues, and put them in the backlog. We should also delegate these tasks so everyone knows what they are doing the following weeks.

**Comment by Mons1Oerjan** [comment]
This will be discussed during our meeting on Sunday March 5th.

**Comment by ericdesj** [comment]
Could you append issue #25 to the meeting's agenda please.

**Comment by Mons1Oerjan** [comment]
Issue 25 was already in the meeting agenda (fix project directory structure). We will do this at our meeting on Sunday.
