### ISSUE TITLE
Organize fragments in separate directories

### ISSUE THREAD

**Issue by ericdesj** [ericdesj/KRUSH#25]
Organize partials in three separate directories: `StudentFragments`, `AppFragments` and `TutorFragments`.

![file_structure](https://cloud.githubusercontent.com/assets/6282512/23579805/bd99f576-00cb-11e7-9674-8ad0bbe518c9.png)

**Note:**
We should do this during this week's team meeting to avoid any merging issues (March 5).

**Comment by Mons1Oerjan** [comment]
this task has been completed.
