### ISSUE TITLE
Disable landscape mode

### ISSUE THREAD

**Issue by ericdesj** [ericdesj/KRUSH#31]
We need to disable landscape mode for the application. Like apps such as Twitter and Facebook our app should only be consumed with a strict portrait orientation.

**Comment by ericdesj** [comment]
Further, we want to avoid this:

![screen shot 2017-03-04 at 9 31 13 pm](https://cloud.githubusercontent.com/assets/6282512/23583756/c9fc53c4-0123-11e7-8a90-eb6d5d60a007.png)

**Comment by Mons1Oerjan** [comment]
This task has been completed, unless you are still working on the situation in that screenshot above..? @ericdesj

**Comment by Mons1Oerjan** [comment]
this task is done.
