### ISSUE TITLE
Student View: Setup Home View (empty view with navigation)

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#5]
Create a new home view with these sections:

- View Tutors
- Booked / Upcoming Sessions
- Navigation bar at the bottom of the view that links to: Home, Quick Book, Edit Profile, and Session History.

This view shows up after a student logs in (defaults to this view).

This is just to get started, so no need for functionality yet.

**Comment by ConnorWalsh7** [comment]
Merged into #14 and will just create one PR
