### ISSUE TITLE
Give team SOAP an A+

### ISSUE THREAD

**Issue by ericdesj** [ericdesj/KRUSH#52]
:zap: :star: :zap: :star: :zap: :star: :zap: :star::zap: :star: :zap: :star::zap: :star: :zap: :star::zap: :star: :zap: :star: :zap: :star: :zap: :star: :zap: :star: :zap: 
**Add an A+ in Brightspace to team SOAP**
:zap: :star: :zap: :star: :zap: :star: :zap: :star::zap: :star: :zap: :star::zap: :star: :zap: :star::zap: :star: :zap: :star: :zap: :star: :zap: :star: :zap: :star: :zap:

**Comment by raghavsampangi** [comment]
Done!
