### ISSUE TITLE
Weekly Meeting 2

### ISSUE THREAD

**Issue by ericdesj** [ericdesj/KRUSH#56]
**Notes posted by @Mons1Oerjan:**
Meeting this Sunday at 12pm in SKL
 Meeting Agenda:
- Work on tasks for Sprint 2
- Share project issues (Eric's video of accessing the DB, Mons' fragment inside a fragment issue)
- Delegate tasks / sections for project update 2

**Comment by ericdesj** [comment]
We should also:
- Standardize how we pass data from Activity/Fragment (i.e. current user, etc)
- Could we have functionality to reset the DB?

**Comment by Mons1Oerjan** [comment]
- Reset the DB: Go to tools -> android -> AVD Manager -> wipe data on your emulator.
- Passing data: Use Bundles, and pass the entire User object (the user that logs in).
- Added new tasks for this Sprint and assigned to Greg and Eric.
