### ISSUE TITLE
Add Payment Information for students

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#61]
As part of our expected functionality, students should be able to set their payment information and pay for a tutoring session.

**Comment by ericdesj** [comment]
<img width="483" alt="screen shot 2017-03-15 at 1 14 30 pm" src="https://cloud.githubusercontent.com/assets/6282512/23958590/582ceb6c-0981-11e7-89d8-e5028cc293a8.png">

**Comment by Mons1Oerjan** [comment]
this task is done. I'm opening a new issue for the todo's that are left
