### ISSUE TITLE
Student Booking select list items

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#73]
Students can view the tutor profile of a given tutor which displays their: name, available subjects, rate per half hour, available time slots, profile picture and description.

Add ability to click on the item in the list view that brings you to a new fragment / view displaying this info.

**Comment by ConnorWalsh7** [comment]
-Added onClick listeners for for both lists on home fragment and booking fragment
-When a list item is clicked the session_id or tutor_id is extracted and passed to new fragment
-session details fragment and tutor details fragment created with basic placeholder info
