### ISSUE TITLE
Student Home select list items

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#74]
Add ability to click on an item in both lists.

Upcoming sessions list:
- Display session information
- Display tutor information
- Display location (on a map)

Quick Book list:
- same as the student booking list item
- Info such as: star rating, rate per hour, available time slots, button to book the tutor, some of his profile info, etc.

**Comment by ConnorWalsh7** [comment]
-Added onClick listeners for for both lists on home fragment and booking fragment
-When a list item is clicked the session_id or tutor_id is extracted and passed to new fragment
-session details fragment and tutor details fragment created with basic placeholder info
