### ISSUE TITLE
Setup DB

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#8]
Follow the instructions for Lab 5 to complete this task.

We want the following tables for this sprint:
- User: id, name, username (email?), password, picture, isTutor.

**Comment by gregpmillr** [comment]
I will have this completed.

Android migration support:
https://developer.android.com/reference/android/database/sqlite/SQLiteOpenHelper.html

**Comment by Mons1Oerjan** [comment]
We are gonna use [SugarORM](https://www.sitepoint.com/5-best-android-orms/) instead of SQLite

**Comment by Mons1Oerjan** [comment]
We should investigate https://realm.io/

**Comment by Mons1Oerjan** [comment]
A separate task has been created for the API (query functions).

**Comment by gregpmillr** [comment]
See PR #38

**Comment by Mons1Oerjan** [comment]
this task is approved, merged, and completed.
