### ISSUE TITLE
Setup list item edit / delete functionality for the Tutor Availability listview

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#95]
In this list item view, the tutor should be able to delete a list item (their available timeslots).

We could either use the touch functionality (sliding the finger to the right on a list item displays edit and delete buttons), or we could use a popup view with an edit form + delete button. 

## Update:
- Clicking on a list item brings you to a new view displaying a list of all available time slots for that day.
- In this new view, the user should be able to delete time slots (touch functionality?)

**Comment by gregpmillr** [comment]
@Mons1Oerjan should it just be delete functionality? I don't see why we'd have edit when it'd just be the same form we already have when adding.

**Comment by Mons1Oerjan** [comment]
only delete. We discussed this during the meeting today. I'll remove it from the description

**Comment by Mons1Oerjan** [comment]
this is done.
